### PR TITLE
Merge latest changes

### PR DESCRIPTION
**Pull request by ZornsLemma**
Hi Ken,

The printer buffer has finally given up most of its secrets and I've moved on (insofar as I have a real plan) to the WRCHV handler, which feels like it might be mostly done too but I'm not sure.

As always please have a look over this and let me have any comments. (I do know some lines with SFTODO comments at the end of an instruction line are ridiculously long, but I don't always like to reformat things for comments which I hope to get rid of eventually.)

Cheers.

Steve

### CODE REVIEW

**Review by kgl2001 — APPROVED** [review]
Now that you're giving labels to all the variables held in Private RAM will it start becoming a bit more difficult to see what registers are actually being used? Especially if these labels are going to be moved to a location closer to the code that they're being used in. It would still be nice to maintain a concise table of registers that are being used in Private RAM, and identify those that are free.

I similarly don't understand why IBOS messes around with the crtc registers. *TV parameters do get saved in the IBOS config, but IIRC, setting *TV parameters in IBOS doesn't require any direct access to the crtc registers.

I'm also not sure why *SHX isn't normally active. As you suggest, it may well be due to the time it takes to switch modes. If we have some free Private RAM that could speed up mode switches, then that might be a good solution. Note that in my IntegraB V2 implementation, I am hoping that we can have a dedicated 16k of 'hidden' RAM area for IBOS workspace. I'm not exactly sure where this would map into yet, though.

**Comment by ZornsLemma** [comment]
Hi Ken,

I did see your comments on pull request #2, but they might only be familiar because you e-mailed me as well. I *think* github will e-mail any comments you make on a pull request to me, but it's hard to be sure. For the next pull request, why don't you *only* comment on the pull request and we'll see if I notice? If you don't close the pull request until you've seen a reply from me that will also mean I'm less likely to miss it.

Thanks for your comments. As for the labels for private RAM, I think having a table is a good idea, as long as we can still have the labels for use in the code. I just haven't been updating the existing tables in the comments as it's all still a work in progress. (I haven't taken the existing table comments and turned them into labels straight away because I prefer not to create a label until I've looked at the associated code at least a bit.)

A dedicated 16K of hidden RAM would be luxurious. :-) Would there be any prospect of using bits 2 and 3 of RAMSEL to help with this? Perhaps (making this up, just as an example) leave bit 2 unused, and treat bit 3 and bit 4 (PRVS8) as a two-bit value identifying one of (up to) 4 8K banks which can be paged in at &9000-AFFF?

On the other hand, if/when we start trying to actually modify rather than disassemble the IBOS ROM I expect we'll get bitten by the difficulty of arranging code in the IBOS ROM where it won't be hidden by the private RAM it's trying to page in and use, so it might be nice if the same idea was used but combining bits 3 and 6 (PRVS1) to allow multiple alternate banks to be paged in at &8000-&83FF. That way IBOS ROM code living anywhere from &8400 up can use these alternate banks without worrying about being hidden by the private RAM.

Obviously there are loads of variants possible here (and it may be that none of them would work or be a good idea in hardware :-) ). I hope this makes sense, even if you don't think it's a good idea or an implementable idea.

Cheers.

Steve

**Comment by ZornsLemma** [comment]
Hi Ken,

I hope you'll see this, please let me know if you do...

I had a quick play around in b-em and it does look like IBOS offers a "horizontal *TV" operation if you manually write to the relevant user RTC register. I've attached a disc image with the following program on it:
```
   10FOR I%=-10 TO 10 STEP 2
   20OSCLI "FX162,54,"+STR$(I% AND &FF)
   30MODE 6
   40VDU 19,0,4,0,0,0
   50PRINT "Hello!"
   60PRINT "Press a key...";
   70IF GET
   80NEXT
```
If you run this you'll see the mode 6 screen moving across the screen, and the change persists over a BREAK and presumably over a power cycle too. You can undo the effect by *FX162,54,0.

I don't know if this is unreliable in some way (perhaps on real hardware it just tends to make the screen collapse?), or maybe just that not useful, but it seems a little odd it wasn't exposed as a *CONFIGURE option. If this *does* work reliably in practice, it would be easy enough to expose it in IBOSv2.
[horizontal-offset.zip](https://github.com/kgl2001/IntegraB-OS/files/6246865/horizontal-offset.zip)

Cheers.

Steve

**Comment by ZornsLemma** [comment]
PS Or of course, if it's not useful, we could delete the supporting code to free up some space for other IBOSv2 features.

**Comment by kgl2001** [comment]
@ZornsLemma 

Hi Steve,

Yes, this message did appear in Github, but it wasn't particularly obvious (at least when browsing via mobile Github). I eventually found the message attached to the 3rd pull request.

I also received the message via email, which is how I was aware that you sent it. Don't get me wrong here, this was a perfectly acceptable way for me to be notified.

I've added an @ to the start of this message to see if it makes the message more obvious in Github directly, and without having to rely on email notifications.

In response to your comment about *TV, I apologise if I was not clear in my previous comment and have caused you extra work here. *TV is a CONFIGURE option. If you type *STATUS in B-Em you should see it listed as an option. I had previously added some comments about it in the Defaults section of the code and it's also shown in the parameters list section. The point I was trying to make earlier is that I didn't think that IBOS needed to write to the crtc controller directly to apply these settings. I seem to recall that this was being applied via certain OS calls.

Ken.

**Comment by kgl2001** [comment]
@ZornsLemma 

Hi Steve,

Thinking about the *SHX option a bit more, and apologies I'm telling you something you already know, but it can be 'permanently' enabled by setting *CONF. SHX ON. As long as you're in any OSMODE other than 0, it should always be active.  This configuration should also survive a reboot, as it's stored in battery backed RAM. The only things that should change it back are either a [Ctrl]-[@]-[Break] and doing a System Reset, or setting *CONF. SHX OFF. It would also be very easy to change the System Reset default for this parameter to 'ON' by setting bit 3 of &8A70 to 1 (setting the value to &0C). See line below:

`		EQUB &32,&04								;0-2: OSMODE / 3: SHX
`

which is included in this section of code:
```
.intDefault	EQUB &06,&FF								;*INSERT status for ROMS &0F to &08. Default: &FF (All 8 ROMS enabled)
		EQUB &07,&FF								;*INSERT status for ROMS &07 to &00. Default: &FF (All 8 ROMS enabled)
;		EQUB &0A,&E7								;0-2: MODE / 3: SHADOW / 4: TV Interlace / 5-7: TV screen shift. Default was &17. Changed to &E7 in IBOS 1.21
;		EQUB &0B,&20								;0-2: FDRIVE / 3-5: CAPS. Default was &23. Changed to &20 in IBOS 1.21
		EQUB &0A,&17								;0-2: MODE / 3: SHADOW / 4: TV Interlace / 5-7: TV screen shift.
		EQUB &0B,&23								;0-2: FDRIVE / 3-5: CAPS.
		EQUB &0C,&19								;0-7: Keyboard Delay
		EQUB &0D,&05								;0-7: Keyboard Repeat
		EQUB &0E,&0A								;0-7: Printer Ignore
		EQUB &0F,&2D								;0: Tube / 2-4: BAUD / 5-7: Printer
;		EQUB &10,&A1								;0: File system / 4: Boot / 5-7: Data. Default was &A0. Changed to &A1 in IBOS 1.21
		EQUB &10,&A0								;0: File system / 4: Boot / 5-7: Data.
		EQUB &32,&04								;0-2: OSMODE / 3: SHX
;		EQUB &35,&14								;Century - Default was &13 (1900). Changed to &14 (2000) in IBOS 1.21
		EQUB &35,&13								;Century - Default is &13 (1900)
		EQUB &38,&FF
		EQUB &39,&FF
		EQUB &3A,&90
		EQUB &7F,&0F								;Bit set if RAM located in 32k bank. Clear if ROM is located in bank. Default is &0F (lowest 4 x 32k banks).
```
The mode change to and from shadow is still quite slow, though, as you've previously pointed out, so if there is an opportunity to improve it, that would be useful.

**Comment by ZornsLemma** [comment]
@kgl2001

Hi Ken,

I'm glad you saw my messages - I was a bit concerned github wouldn't e-mail them out as I was commenting on a closed pull request, although I suppose it makes sense that it would. I don't know if the "@" makes any difference or not; I did get e-mailed your message, but I think I got e-mailed the other ones too.

I remember we discussed the *CONFIGURE SHX option in the Ozmoo thread. It would be nice if we could optimise this enough that it's reasonable to change the default CMOS values so this is on by default. I don't think we're in any kind of disagreement, but just let me waffle for a couple of paragraphs about this to try to be clear where I'm coming from. FWIW I don't have any strong views on changing the default if we *can't* optimise this; I could see arguments both ways.

I have never used shadow RAM on a model B outside of an emulator - my model B BITD only had sideways RAM. On the Master and B+ shadow RAM seems to "just work" most of the time, whereas we hit that problem with Ozmoo which turned out to be caused by switching into a shadow mode with BASIC code above &3000 with SHX OFF. As with a lot of 8-bit Acorn quirks, once you know about this it's easy enough to work around, but trying to translate this experience into a user perspective, it just feels like a shame the user is encouraged (by the default and by the slowness of mode changes) to have SHX OFF when it will cause the odd unexplained crash in programs written and tested on a B+/Master.

It's nice the Integra-B offers the option of speed or safety; I think other shadow RAM boards may have only offered the speed option. (I have memories of comments from sweh on various stardot posts suggesting the Solidisk shadow RAM had a similar problem and he had to write his own manager ROM to do what IBOS does in SHX mode.) Wearing my software developer hat, it doesn't matter if we improve Integra-B here at all, because I still want my software to work on those other systems which exhibit this quirk when changing from non-shadow to shadow mode. (This is why I didn't fix this in Ozmoo by using the *SHX command, because that wouldn't fix it on those other boards.) But improving this would benefit users, who would be less likely to experience problems because software has been developed with B+/Master style shadow RAM.

On *TV, I think I might not have been clear. What you say makes perfect sense. I see there's code in the service01 handler at L9736 to implement the *CONFIGURE TV adjustment by calling the OS *TV command, so IBOS is leaving the relevant CRTC adjustments up to the OS.

However, it looks like the IBOS ROM *also* has 90% of the code present to implement a (making the name up) "*CONFIGURE HorizontalTV" option which shifts the display left and right instead of up and down, and this is what the unexplained CRTC writes are for. Everything seems to be present except code to expose this in *CONFIGURE/*STATUS. By setting RTC address 54 directly using *FX162,54, at least in b-em I am able to get IBOS to "permanently" adjust the screen left/right position. Apologies if you already got that; I appreciate you might have been just clarifying what you said earlier about *TV, but I thought I should be explicit about this just in case.

Cheers.

Steve

PS I added an @ at the start of this message, but only by editing after I originally posted it without the @. I don't know if that's helpful or not...

**Comment by kgl2001** [comment]
I don't think the @ actually makes any difference. I'm pretty sure I got the email notification when you made your initial post. I've left it out this time, so let's see...

I've been browsing the IBOS manual that came with the 1.20 ROM, and noticed that there are a number of differences from the manual that's available online (I scanned that one in and OCRd it many years ago). Once specific area that's different is that there's a section that talks about the Shadow RAM. I've scanned that bit in, OCRd it and attached it for your information. I'll do the rest of the manual sometime soon.

[IBOS1.20-Shadow RAM.pdf](https://github.com/kgl2001/IntegraB-OS/files/6250400/IBOS1.20-Shadow.RAM.pdf)

Sorry, I misunderstood your earlier comments about the Horizontal crtc shift. You do see the effects of the horizontal shift occasionally on boot, and if things get corrupt. In particular, when the RTC is missing from the board or if IBOS is otherwise unable to get data from the RTC, you can see the whole screen shift significantly to the right. I'm not sure what benefit you get from doing this left / right shifting?

**Comment by kgl2001** [comment]
Hi Steve,

I see you're still busy making commits. You seem to be making really 
good progress! I just wanted to check that you've picked up the comments 
I left on a couple of your commits? I'm not sure if you got a 
notification when I left those comments. I certainly didn't.

Thanks

Ken.

On 2021-04-02 14:51, ZornsLemma wrote:

> Hi Ken,
> 
> I'm glad you saw my messages - I was a bit concerned github wouldn't 
> e-mail them out as I was commenting on a closed pull request, although 
> I suppose it makes sense that it would. I don't know if the "@" makes 
> any difference or not; I did get e-mailed your message, but I think I 
> got e-mailed the other ones too.
> 
> I remember we discussed the *CONFIGURE SHX option in the Ozmoo thread. 
> It would be nice if we could optimise this enough that it's reasonable 
> to change the default CMOS values so this is on by default. I don't 
> think we're in any kind of disagreement, but just let me waffle for a 
> couple of paragraphs about this to try to be clear where I'm coming 
> from. FWIW I don't have any strong views on changing the default if we 
> _can't_ optimise this; I could see arguments both ways.
> 
> I have never used shadow RAM on a model B outside of an emulator - my 
> model B BITD only had sideways RAM. On the Master and B+ shadow RAM 
> seems to "just work" most of the time, whereas we hit that problem with 
> Ozmoo which turned out to be caused by switching into a shadow mode 
> with BASIC code above &3000 with SHX OFF. As with a lot of 8-bit Acorn 
> quirks, once you know about this it's easy enough to work around, but 
> trying to translate this experience into a user perspective, it just 
> feels like a shame the user is encouraged (by the default and by the 
> slowness of mode changes) to have SHX OFF when it will cause the odd 
> unexplained crash in programs written and tested on a B+/Master.
> 
> It's nice the Integra-B offers the option of speed or safety; I think 
> other shadow RAM boards may have only offered the speed option. (I have 
> memories of comments from sweh on various stardot posts suggesting the 
> Solidisk shadow RAM had a similar problem and he had to write his own 
> manager ROM to do what IBOS does in SHX mode.) Wearing my software 
> developer hat, it doesn't matter if we improve Integra-B here at all, 
> because I still want my software to work on those other systems which 
> exhibit this quirk when changing from non-shadow to shadow mode. (This 
> is why I didn't fix this in Ozmoo by using the *SHX command, because 
> that wouldn't fix it on those other boards.) But improving this would 
> benefit users, who would be less likely to experience problems because 
> software has been developed with B+/Master style shadow RAM.
> 
> On *TV, I think I might not have been clear. What you say makes me 
> perfect sense. I see there's code in the service01 handler at L9736 to 
> implement the *CONFIGURE TV adjustment by calling the OS *TV command, 
> so IBOS is leaving the relevant CRTC adjustments up to the OS.
> 
> However, it looks like the IBOS ROM _also_ has 90% of the code present 
> to implement a (making the name up) "*CONFIGURE HorizontalTV" option 
> which shifts the display left and right instead of up and down, and 
> this is what the unexplained CRTC writes are for. Everything seems to 
> be present except code to expose this in *CONFIGURE/*STATUS. By setting 
> RTC address 54 directly using *FX162,54, at least in b-em I am able to 
> get IBOS to "permanently" adjust the screen left/right position. 
> Apologies if you already got that; I appreciate you might have been 
> just clarifying what you said earlier about *TV, but I thought I should 
> be explicit about this just in case.
> 
> Cheers.
> 
> Steve
> 
> --
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].


Links:
------
[1] https://github.com/kgl2001/IntegraB-OS/pull/3#issuecomment-812539603
[2]

**Pull request merged**
